apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-a-ingress
spec:
  rules:
    - host: api-a.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-a
                port:
                  number: 80
