apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-b
  template:
    metadata:
      labels:
        app: api-b
    spec:
      containers:
      - name: api-b
        image: ys8o/api-b:latest
        ports:
        - containerPort: 80